#!/bin/sh

# config {{{

bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9'

bspc config border_width  2
bspc config window_gap   16

bspc config split_ratio        0.5
bspc config borderless_monocle true
bspc config gapless_monocle    true

# }}}

# autorun {{{

feh --bg-max ~/Pictures/wallpapers/wallpaper-01.jpg
picom -b
xset r rate 300 30

dunst &
fcitx5 -rd &
polybar okayurisotto &
sxhkd &
xss-lock -- i3lock &

# }}}
